version: "3.7"

volumes:
  database:
    name: database

services:
  front:
    build: ./front/
    ports:
      - "3000:3000"
  game:
    build: ./game/
    ports:
      - "8081:8080"
  login:
    build: ./login/
    ports:
      - "8080:8080"
  matchmaking:
    build: ./matchmaking/
    ports:
      - "8083:8080"
  users:
    build: ./users/
    ports:
      - "8082:8080"

  database:
    container_name: database
    build: ./postgresql/
    image: database

    # Data persistance
    volumes:
      - 'database:/var/lib/postgresql/data'

    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'pong'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
  
  # web:
  #   build: ./back/
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - db
  # db:
  #   image: postgres:12-alpine
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=postgres
  # volumes:
  #   postgres_data:
  #     driver: local
  #     driver_opts:
  #       type: none
  #       device: ${HOME}/data/postgres
  #       o: bind
