version: "3.9"

services:
  front:
    container_name: front
    build: ./front/
    image: front

    ports:
      - "3000:3000"

    networks:
      - "internal_microservice"

    environment:
      LOGIN_42: ${LOGIN_42}

    restart: on-failure

  game:
    build: ./game/
    ports:
      - "8083:8080"
    networks:
      - "internal_microservice"

  login:
    build: ./login/
    ports:
      - "8080:80"
    env_file:
      - "./.env.dockerized" # All the environment, for facilitating development
    networks:
      - "internal_microservice"

  matchmaking:
    build: ./matchmaking/
    ports:
      - "8084:8080"
    networks:
      - "internal_microservice"

  users:
    build: ./users/
    ports:
      - "8081:80"
    env_file:
      - "./.env.dockerized" # All the environment, for facilitating development
    networks:
      - "internal_microservice"

  notifications:
    build: ./notifications/
    ports:
      - "8082:80"
    env_file:
      - "./.env.dockerized" # All the environment, for facilitating development
    networks:
      - "internal_microservice"

  redis: # TODO: Make it secure with credentials
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - "internal_microservice"

  database:
    container_name: database
    build: ./postgresql/
    image: database
    ports:
      - '5432:5432'
    networks:
      - "internal_microservice"
    environment:
      POSTGRES_DB: 'pong'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres' # TODO: get from env

      #    # Data persistance commented for development purposes
      #    volumes:
      #      - 'database:/var/lib/postgresql/data'

networks:
  internal_microservice:

volumes:
  database:
    name: database
