version: "3.9"

services:
  endpoint:
    container_name: endpoint
    build: ./endpoint/
    image: endpoint

    ports:
      - "443:443"
      - "80:80"
    networks:
      - "internal_microservice"
    volumes:
      - './volumes/static:/static'
    
    depends_on:
      - front
    restart: on-failure

  front:
    container_name: front
    build: ./front/
    image: front

    networks:
      - "internal_microservice"
    volumes:
      - './volumes/static:/static'
    env_file:
      - "./.env.dockerized" # All the environment, for facilitating development

    depends_on:
      database:
        condition: service_healthy

    restart: on-failure

  game:
    container_name: game
    build: ./game/
    image: game

    networks:
      - "internal_microservice"

    restart: on-failure

  login:
    container_name: login
    build: ./login/
    image: login
    env_file:
      - "./.env.dockerized" # All the environment, for facilitating development
    networks:
      - "internal_microservice"

    restart: on-failure

  matchmaking:
    container_name: matchmaking
    build: ./matchmaking/
    image: matchmaking

    networks:
      - "internal_microservice"

    restart: on-failure

  users:
    container_name: users
    build: ./users/
    image: users

    env_file:
      - "./.env.dockerized" # All the environment, for facilitating development
    networks:
      - "internal_microservice"
    restart: on-failure

  notifications:
    container_name: notifications
    build: ./notifications/
    image: notifications

    env_file:
      - "./.env.dockerized" # All the environment, for facilitating development
    networks:
      - "internal_microservice"

    restart: on-failure

  redis: # TODO: Make it secure with credentials
    container_name: redis
    image: redis:7.2.3-alpine
    ports:
      - "6379:6379"
    networks:
      - "internal_microservice"

  database:
    container_name: database
    build: ./database/
    image: database

    networks:
      - "internal_microservice"

      #    # Data persistance commented for development purposes
      #    volumes:
      #      - './volumes/database:/var/lib/postgresql/data'
      #
    env_file:
      - "./.env.dockerized" # All the environment, for facilitating development

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

    restart: on-failure

networks:
  internal_microservice:
    driver: bridge
    name: "internal_microservice"
